/**
 * Configuration constants for environment variables
 * Using constants/enums instead of string literals improves maintainability and type safety
 */
export enum ENV {
  NODE_ENV = 'NODE_ENV',
  JWT_ACCESS_TOKEN_SECRET = 'JWT_ACCESS_TOKEN_SECRET',
  JWT_REFRESH_TOKEN_SECRET = 'JWT_REFRESH_TOKEN_SECRET',
  JWT_ACCESS_TOKEN_EXPIRATION_TIME_MS = 'JWT_ACCESS_TOKEN_EXPIRATION_TIME_MS',
  JWT_REFRESH_TOKEN_EXPIRATION_TIME_MS = 'JWT_REFRESH_TOKEN_EXPIRATION_TIME_MS',
  MONGODB_URI = 'MONGODB_URI',
  AUTH_UI_REDIRECT_URL = 'AUTH_UI_REDIRECT_URL',
}
