version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    restart: always
    container_name: postgres_frankenstein
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ['CMD-SHELL', "sh -c 'pg_isready -U postgres -d postgres'"]
      interval: 10s
      timeout: 3s
      retries: 3
    entrypoint: >
      sh -c "
        if [ ! -f /var/lib/postgresql/data/.initialized ]; then
          docker-entrypoint.sh postgres &
          sleep 10 &&
          psql -U postgres -tc \"SELECT 1 FROM pg_database WHERE datname = 'aerobus'\" | grep -q 1 || psql -U postgres -c 'CREATE DATABASE aerobus;' &&
          psql -U postgres -tc \"SELECT 1 FROM pg_database WHERE datname = 'aerobus_strapi'\" | grep -q 1 || psql -U postgres -c 'CREATE DATABASE aerobus_strapi;' &&
          touch /var/lib/postgresql/data/.initialized
        else
          docker-entrypoint.sh postgres
        fi
      "

volumes:
  pgdata:
